import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, extname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { spawnSync } from "node:child_process";
import type { Manifest } from "./manifest.js";
import { validateManifest } from "./manifest.js";
import type { CalibrateRoute } from "./route-observer.js";
import { validateRoutes } from "./route-observer.js";
import { CALIBRATE_VERSION } from "./version.js";

export const INSTALL_SCHEMA_VERSION = 1;
export const INSTALL_CONFIG_FILE = "calibrate.install.json";
export const GENERATED_MARKER = "// Generated by Calibrate. Edit calibrate.install.json and re-run planning.";
export const ENTRY_MARKER = "// Calibrate instrumentation";

export type ProjectKind = "react-vite" | "generic-esm" | "unsupported";
export type DetectionStatus = "supported" | "needs_human_judgment" | "blocked";

export interface RouteCandidate extends CalibrateRoute {
  source: string;
  proposed: true;
}

export interface ProjectDetection {
  v: 1;
  command: "detect";
  targetDir: string;
  status: DetectionStatus;
  projectKind: ProjectKind;
  framework: string;
  packageManager: "npm" | "pnpm" | "yarn" | "bun" | "unknown";
  packageFile: string | null;
  entryFile: string | null;
  existingInstallation: boolean;
  routeCandidates: RouteCandidate[];
  issues: string[];
}

export interface PlannedChange {
  path: string;
  action: "create" | "modify" | "unchanged";
  beforeSha256: string | null;
  content: string;
}

export interface InstallConfiguration {
  v: 1;
  package: "usecalibrate";
  collector: {
    mode: "sidecar";
    endpoint: string;
  };
  manifest: Manifest;
  routes: CalibrateRoute[];
  entryFile: string;
  integrationFile: string;
}

export interface InstallPlan {
  v: 1;
  command: "plan";
  planId: string;
  targetDir: string;
  status: "ready" | "needs_human_judgment" | "blocked";
  detection: ProjectDetection;
  configuration: InstallConfiguration | null;
  changes: PlannedChange[];
  installCommand: string[] | null;
  requiredEnvironment: string[];
  decisions: string[];
  issues: string[];
}

export interface ApplyResult {
  v: 1;
  command: "apply";
  status: "applied" | "blocked";
  targetDir: string;
  planId: string;
  changedFiles: string[];
  unchangedFiles: string[];
  installCommand: string[] | null;
  installExitCode: number | null;
  issues: string[];
}

export interface VerificationCheck {
  name: string;
  ok: boolean;
  detail: string;
}

export interface VerifyResult {
  v: 1;
  command: "verify";
  status: "verified" | "failed";
  evidence: "artifact" | "runtime";
  targetDir: string;
  checks: VerificationCheck[];
}

interface PackageDocument {
  name?: string;
  type?: string;
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
}

export interface PlanOptions {
  routes?: CalibrateRoute[];
  endpoint?: string;
  manifest?: Manifest;
}

export interface ApplyOptions {
  install?: boolean;
  quiet?: boolean;
}

function planIdentifier(
  targetDir: string,
  configuration: InstallConfiguration,
  changes: PlannedChange[],
): string {
  return sha256(JSON.stringify({ targetDir, configuration, changes }));
}

export interface VerifyOptions {
  endpoint?: string;
  writeKey?: string;
}

export interface CollectorDiscovery {
  v: 1;
  command: "discover-collector";
  status: "ready" | "blocked";
  endpoint: string | null;
  dashboardUrl: string | null;
  manifest: Manifest | null;
  checks: VerificationCheck[];
  issues: string[];
}

export interface GuidedInstallPreparation {
  v: 1;
  command: "install";
  status: "ready" | "needs_human_judgment" | "blocked";
  targetDir: string;
  collector: CollectorDiscovery;
  plan: InstallPlan | null;
}

export interface GuidedInstallResult {
  v: 1;
  command: "install";
  status: "installed" | "partial" | "blocked";
  evidence: "none" | "artifact" | "runtime";
  targetDir: string;
  collectorUrl: string | null;
  dashboardUrl: string | null;
  hosting: {
    browserSdk: "bundled-with-application";
    collector: "existing-standalone-or-embedded-service";
    dashboard: "served-by-collector";
  };
  changedFiles: string[];
  unchangedFiles: string[];
  requiredEnvironment: string[];
  checks: VerificationCheck[];
  issues: string[];
}

export interface GuidedInstallOptions {
  writeKey?: string;
  install?: boolean;
  quiet?: boolean;
}

function sha256(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

export function normalizeCollectorUrl(value: string): string {
  let parsed: URL;
  try {
    parsed = new URL(value);
  } catch {
    throw new Error("collector URL must be an absolute http or https URL");
  }
  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    throw new Error("collector URL must use http or https");
  }
  if (parsed.username !== "" || parsed.password !== "") {
    throw new Error("collector URL must not contain credentials");
  }
  if (parsed.search !== "" || parsed.hash !== "") {
    throw new Error("collector URL must not contain a query or fragment");
  }
  parsed.pathname = parsed.pathname === "/"
    ? ""
    : parsed.pathname.replace(/\/+$/, "");
  return parsed.toString().replace(/\/$/, "");
}

export async function discoverCollector(value: string): Promise<CollectorDiscovery> {
  let endpoint: string;
  try {
    endpoint = normalizeCollectorUrl(value);
  } catch (error) {
    return {
      v: 1,
      command: "discover-collector",
      status: "blocked",
      endpoint: null,
      dashboardUrl: null,
      manifest: null,
      checks: [],
      issues: [error instanceof Error ? error.message : "collector URL is invalid"],
    };
  }
  const dashboardUrl = `${endpoint}/dashboard`;
  const checks: VerificationCheck[] = [];
  let manifest: Manifest | null = null;
  try {
    const health = await fetch(`${endpoint}/healthz`, {
      headers: { Accept: "application/json" },
      signal: AbortSignal.timeout(10_000),
    });
    checks.push({
      name: "collector-health",
      ok: health.ok,
      detail: `GET /healthz returned ${health.status}`,
    });
    if (!health.ok) throw new Error("collector health check failed");

    const manifestResponse = await fetch(`${endpoint}/api/manifest`, {
      headers: { Accept: "application/json" },
      signal: AbortSignal.timeout(10_000),
    });
    if (!manifestResponse.ok) {
      checks.push({
        name: "collector-manifest",
        ok: false,
        detail: `GET /api/manifest returned ${manifestResponse.status}`,
      });
      throw new Error("collector manifest is unavailable");
    }
    try {
      const discoveredManifest = validateManifest(await manifestResponse.json());
      manifest = discoveredManifest;
      checks.push({
        name: "collector-manifest",
        ok: true,
        detail: `manifest ${discoveredManifest.version} has ${discoveredManifest.steps.length} steps`,
      });
    } catch (error) {
      checks.push({
        name: "collector-manifest",
        ok: false,
        detail: error instanceof Error ? error.message : "collector manifest is invalid",
      });
      throw new Error("collector manifest is invalid");
    }

    const dashboard = await fetch(dashboardUrl, {
      headers: { Accept: "text/html" },
      signal: AbortSignal.timeout(10_000),
    });
    const dashboardReady = dashboard.ok &&
      (dashboard.headers.get("content-type") ?? "").includes("text/html");
    checks.push({
      name: "collector-dashboard",
      ok: dashboardReady,
      detail: `GET /dashboard returned ${dashboard.status}`,
    });
    if (!dashboardReady) throw new Error("collector dashboard is unavailable");
  } catch (error) {
    return {
      v: 1,
      command: "discover-collector",
      status: "blocked",
      endpoint,
      dashboardUrl,
      manifest: null,
      checks,
      issues: [error instanceof Error ? error.message : "collector discovery failed"],
    };
  }
  return {
    v: 1,
    command: "discover-collector",
    status: "ready",
    endpoint,
    dashboardUrl,
    manifest,
    checks,
    issues: [],
  };
}

function readText(path: string): string | null {
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}

function readPackage(path: string): PackageDocument | null {
  const content = readText(path);
  if (content === null) return null;
  try {
    return JSON.parse(content) as PackageDocument;
  } catch {
    return null;
  }
}

function dependencyNames(document: PackageDocument): Set<string> {
  return new Set([
    ...Object.keys(document.dependencies ?? {}),
    ...Object.keys(document.devDependencies ?? {}),
  ]);
}

function packageManager(targetDir: string): ProjectDetection["packageManager"] {
  if (existsSync(join(targetDir, "pnpm-lock.yaml"))) return "pnpm";
  if (existsSync(join(targetDir, "yarn.lock"))) return "yarn";
  if (existsSync(join(targetDir, "bun.lock")) || existsSync(join(targetDir, "bun.lockb"))) return "bun";
  if (existsSync(join(targetDir, "package-lock.json"))) return "npm";
  return existsSync(join(targetDir, "package.json")) ? "npm" : "unknown";
}

function sourceFiles(targetDir: string): string[] {
  const root = join(targetDir, "src");
  if (!existsSync(root) || !statSync(root).isDirectory()) return [];
  const files: string[] = [];
  const visit = (directory: string): void => {
    if (files.length >= 300) return;
    for (const name of readdirSync(directory)) {
      if (files.length >= 300) return;
      const path = join(directory, name);
      const stat = statSync(path);
      if (stat.isDirectory()) visit(path);
      else if (/\.(?:[cm]?[jt]sx?)$/.test(name)) files.push(path);
    }
  };
  visit(root);
  return files;
}

function findEntry(targetDir: string, files: string[]): string | null {
  const candidates = [
    "src/main.tsx",
    "src/main.ts",
    "src/main.jsx",
    "src/main.js",
    "src/index.tsx",
    "src/index.ts",
    "src/index.jsx",
    "src/index.js",
    "src/app.ts",
    "src/app.js",
  ];
  for (const candidate of candidates) {
    if (existsSync(join(targetDir, candidate))) return candidate;
  }
  return files.length === 1 ? relative(targetDir, files[0] as string) : null;
}

function machineId(pathname: string): string {
  const parts = pathname.split("/").filter(Boolean);
  const raw = parts.at(-1) ?? "home";
  const normalized = raw
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return normalized === "" ? "step" : normalized.slice(0, 128);
}

function routeCandidates(targetDir: string, files: string[]): RouteCandidate[] {
  const found = new Map<string, RouteCandidate>();
  const patterns = [
    /\bpath\s*[:=]\s*["'](\/[A-Za-z0-9._/-]*)["']/g,
    /<Route\b[^>]*\bpath=["'](\/[A-Za-z0-9._/-]*)["']/g,
  ];
  for (const file of files) {
    const content = readFileSync(file, "utf8");
    for (const pattern of patterns) {
      pattern.lastIndex = 0;
      for (const match of content.matchAll(pattern)) {
        const path = match[1];
        if (path === undefined || path.includes(":")) continue;
        const id = machineId(path);
        const shipped = /^(?:success|done|complete|completed|finished)$/.test(id);
        found.set(path, {
          path,
          step: id,
          ...(shipped ? { shipped: true } : {}),
          source: relative(targetDir, file),
          proposed: true,
        });
      }
    }
  }
  return [...found.values()];
}

export function detectProject(directory: string): ProjectDetection {
  const targetDir = resolve(directory);
  const packagePath = join(targetDir, "package.json");
  const document = readPackage(packagePath);
  if (document === null) {
    return {
      v: 1,
      command: "detect",
      targetDir,
      status: "blocked",
      projectKind: "unsupported",
      framework: "unknown",
      packageManager: packageManager(targetDir),
      packageFile: existsSync(packagePath) ? "package.json" : null,
      entryFile: null,
      existingInstallation: false,
      routeCandidates: [],
      issues: [existsSync(packagePath) ? "package.json is not valid JSON" : "package.json was not found"],
    };
  }

  const dependencies = dependencyNames(document);
  const files = sourceFiles(targetDir);
  const entryFile = findEntry(targetDir, files);
  const next = dependencies.has("next");
  const vite = dependencies.has("vite");
  const react = dependencies.has("react");
  const kind: ProjectKind = next
    ? "unsupported"
    : vite && react
      ? "react-vite"
      : document.type === "module" || vite
        ? "generic-esm"
        : "unsupported";
  const framework = next ? "next" : vite && react ? "react-vite" : vite ? "vite" : document.type === "module" ? "esm" : "unknown";
  const existingInstallation = files.some((file) => readFileSync(file, "utf8").includes('from "usecalibrate"') || readFileSync(file, "utf8").includes("from 'usecalibrate'"));
  const routes = routeCandidates(targetDir, files);
  const issues: string[] = [];
  if (kind === "unsupported") issues.push(next ? "Next.js is not supported by the v1 installer" : "the project is not a supported ESM browser application");
  if (entryFile === null) issues.push("a unique browser entry file could not be identified");
  if (existingInstallation && !existsSync(join(targetDir, INSTALL_CONFIG_FILE))) issues.push("an existing custom Calibrate integration requires review before automated changes");
  if (routes.length < 2) issues.push("at least two fixed onboarding routes must be supplied or discovered");
  const hardBlocked = kind === "unsupported" || entryFile === null || (existingInstallation && !existsSync(join(targetDir, INSTALL_CONFIG_FILE)));

  return {
    v: 1,
    command: "detect",
    targetDir,
    status: hardBlocked ? "blocked" : routes.length < 2 ? "needs_human_judgment" : "supported",
    projectKind: kind,
    framework,
    packageManager: packageManager(targetDir),
    packageFile: "package.json",
    entryFile,
    existingInstallation,
    routeCandidates: routes,
    issues,
  };
}

function normalizeRoutes(routes: readonly CalibrateRoute[]): CalibrateRoute[] {
  const unique = new Map<string, CalibrateRoute>();
  for (const route of routes) unique.set(route.path, { ...route });
  return [...unique.values()];
}

function manifestFor(routes: readonly CalibrateRoute[]): Manifest {
  return validateManifest({
    version: "onboarding-v1",
    groups: ["onboarding"],
    steps: routes.map((route) => ({ id: route.step, group: "onboarding" })),
  });
}

function integrationSource(kind: ProjectKind, config: InstallConfiguration): string {
  const manifest = JSON.stringify(config.manifest, null, 2);
  const routes = JSON.stringify(config.routes, null, 2);
  if (kind === "react-vite") {
    return `${GENERATED_MARKER}\nimport { calibrate, defineManifest } from "usecalibrate";\n\nexport const calibrateManifest = defineManifest(${manifest});\nexport const calibrateRoutes = ${routes};\n\nconst writeKey = import.meta.env.VITE_CALIBRATE_WRITE_KEY;\nconst endpoint = import.meta.env.VITE_CALIBRATE_ENDPOINT || ${JSON.stringify(config.collector.endpoint)};\n\nexport const calibrateClient =\n  typeof writeKey === "string" && writeKey.length > 0\n    ? calibrate({ endpoint, manifest: calibrateManifest, routes: calibrateRoutes, writeKey })\n    : undefined;\n`;
  }

  const typed = /\.tsx?$/.test(config.integrationFile);
  const configRead = typed
    ? `(globalThis as typeof globalThis & { CALIBRATE_CONFIG?: { endpoint?: string; writeKey?: string } }).CALIBRATE_CONFIG`
    : "globalThis.CALIBRATE_CONFIG";
  return `${GENERATED_MARKER}\nimport { calibrate, defineManifest } from "usecalibrate";\n\nexport const calibrateManifest = defineManifest(${manifest});\nexport const calibrateRoutes = ${routes};\n\nconst runtimeConfig = ${configRead};\nexport const calibrateClient =\n  typeof runtimeConfig?.writeKey === "string" && runtimeConfig.writeKey.length > 0\n    ? calibrate({\n        endpoint: runtimeConfig.endpoint || ${JSON.stringify(config.collector.endpoint)},\n        manifest: calibrateManifest,\n        routes: calibrateRoutes,\n        writeKey: runtimeConfig.writeKey,\n      })\n    : undefined;\n`;
}

function plannedChange(targetDir: string, path: string, content: string): PlannedChange {
  const previous = readText(join(targetDir, path));
  return {
    path,
    action: previous === null ? "create" : previous === content ? "unchanged" : "modify",
    beforeSha256: previous === null ? null : sha256(previous),
    content,
  };
}

function updateEntry(previous: string, integrationFile: string, entryFile: string): string {
  if (previous.includes(ENTRY_MARKER)) return previous;
  const fromDirectory = dirname(entryFile);
  let specifier = relative(fromDirectory, integrationFile).replaceAll("\\", "/");
  if (!specifier.startsWith(".")) specifier = `./${specifier}`;
  specifier = specifier.replace(/\.(?:[cm]?[jt]sx?)$/, "");
  return `${ENTRY_MARKER}\nimport ${JSON.stringify(specifier)};\n${previous}`;
}

function updatedPackage(document: PackageDocument, manager: ProjectDetection["packageManager"]): string {
  const next: PackageDocument = JSON.parse(JSON.stringify(document)) as PackageDocument;
  next.dependencies = { ...next.dependencies, usecalibrate: `^${CALIBRATE_VERSION}` };
  next.scripts = { ...next.scripts, "calibrate:sidecar": "calibrate sidecar --dir ." };
  void manager;
  return `${JSON.stringify(next, null, 2)}\n`;
}

function installCommand(manager: ProjectDetection["packageManager"]): string[] | null {
  if (manager === "npm") return ["npm", "install"];
  if (manager === "pnpm") return ["pnpm", "install"];
  if (manager === "yarn") return ["yarn", "install"];
  if (manager === "bun") return ["bun", "install"];
  return null;
}

export function planInstall(directory: string, options: PlanOptions = {}): InstallPlan {
  const detection = detectProject(directory);
  const routes = normalizeRoutes(options.routes ?? detection.routeCandidates.map(({ source: _source, proposed: _proposed, ...route }) => route));
  const issues = [...detection.issues].filter((issue) => !issue.startsWith("at least two fixed onboarding routes"));
  if (detection.projectKind === "unsupported" || detection.entryFile === null || detection.status === "blocked" && !detection.issues.every((issue) => issue.startsWith("at least two fixed onboarding routes"))) {
    const body = { targetDir: detection.targetDir, status: "blocked", detection, issues };
    return {
      v: 1,
      command: "plan",
      planId: sha256(JSON.stringify(body)),
      targetDir: detection.targetDir,
      status: "blocked",
      detection,
      configuration: null,
      changes: [],
      installCommand: null,
      requiredEnvironment: [],
      decisions: [],
      issues,
    };
  }
  if (routes.length < 2) {
    const body = { targetDir: detection.targetDir, status: "needs_human_judgment", routes };
    return {
      v: 1,
      command: "plan",
      planId: sha256(JSON.stringify(body)),
      targetDir: detection.targetDir,
      status: "needs_human_judgment",
      detection,
      configuration: null,
      changes: [],
      installCommand: null,
      requiredEnvironment: [],
      decisions: ["Supply at least two fixed onboarding routes and identify which route means shipped."],
      issues: ["onboarding semantics are insufficient for an installation plan"],
    };
  }

  let manifest: Manifest;
  try {
    manifest = options.manifest === undefined
      ? manifestFor(routes)
      : validateManifest(options.manifest);
    validateRoutes(routes, manifest);
  } catch (error) {
    const message = error instanceof Error ? error.message : "route mapping is invalid";
    const body = { targetDir: detection.targetDir, status: "needs_human_judgment", routes, message };
    return {
      v: 1,
      command: "plan",
      planId: sha256(JSON.stringify(body)),
      targetDir: detection.targetDir,
      status: "needs_human_judgment",
      detection,
      configuration: null,
      changes: [],
      installCommand: null,
      requiredEnvironment: [],
      decisions: ["Map each fixed application route to a step in the collector manifest."],
      issues: [`route mapping does not match the collector manifest: ${message}`],
    };
  }
  const shippedRoutes = routes.filter((route) => route.shipped === true);
  if (shippedRoutes.length !== 1) {
    const body = { targetDir: detection.targetDir, status: "needs_human_judgment", routes, shippedRoutes: shippedRoutes.length };
    return {
      v: 1,
      command: "plan",
      planId: sha256(JSON.stringify(body)),
      targetDir: detection.targetDir,
      status: "needs_human_judgment",
      detection,
      configuration: null,
      changes: [],
      installCommand: null,
      requiredEnvironment: [],
      decisions: ["Mark exactly one fixed route as the shipped outcome."],
      issues: [`expected exactly one shipped route, found ${shippedRoutes.length}`],
    };
  }
  const entryFile = detection.entryFile;
  const entryExtension = extname(entryFile);
  const integrationExtension = entryExtension === ".tsx" ? ".ts" : entryExtension === ".jsx" ? ".js" : entryExtension;
  const integrationFile = join(dirname(entryFile), `calibrate${integrationExtension}`).replaceAll("\\", "/");
  const configuration: InstallConfiguration = {
    v: INSTALL_SCHEMA_VERSION,
    package: "usecalibrate",
    collector: { mode: "sidecar", endpoint: options.endpoint ?? "http://localhost:8787" },
    manifest,
    routes,
    entryFile,
    integrationFile,
  };
  const packagePath = join(detection.targetDir, "package.json");
  const packageDocument = readPackage(packagePath);
  if (packageDocument === null) throw new Error("package.json became unreadable during planning");
  const entryContent = readText(join(detection.targetDir, entryFile));
  if (entryContent === null) throw new Error("entry file became unreadable during planning");
  const changes = [
    plannedChange(detection.targetDir, "package.json", updatedPackage(packageDocument, detection.packageManager)),
    plannedChange(detection.targetDir, INSTALL_CONFIG_FILE, `${JSON.stringify(configuration, null, 2)}\n`),
    plannedChange(detection.targetDir, integrationFile, integrationSource(detection.projectKind, configuration)),
    plannedChange(detection.targetDir, entryFile, updateEntry(entryContent, integrationFile, entryFile)),
  ];
  return {
    v: 1,
    command: "plan",
    planId: planIdentifier(detection.targetDir, configuration, changes),
    targetDir: detection.targetDir,
    status: "ready",
    detection,
    configuration,
    changes,
    installCommand: installCommand(detection.packageManager),
    requiredEnvironment: detection.projectKind === "react-vite"
      ? ["VITE_CALIBRATE_WRITE_KEY", "ADMIN_TOKEN", "DASHBOARD_TOKEN", "WRITE_KEY"]
      : ["CALIBRATE_CONFIG.writeKey", "ADMIN_TOKEN", "DASHBOARD_TOKEN", "WRITE_KEY"],
    decisions: ["Review and approve the proposed route meanings and shipped route before apply."],
    issues,
  };
}

function validateReadyPlan(plan: InstallPlan): string[] {
  const issues: string[] = [];
  if (plan.v !== INSTALL_SCHEMA_VERSION || plan.command !== "plan") issues.push("plan schema is not supported");
  if (resolve(plan.targetDir) !== plan.targetDir) issues.push("plan targetDir must be absolute");
  if (plan.configuration === null) return [...issues, "plan configuration is missing"];
  try {
    const manifest = validateManifest(plan.configuration.manifest);
    validateRoutes(plan.configuration.routes, manifest);
  } catch (error) {
    issues.push(error instanceof Error ? `plan configuration is invalid: ${error.message}` : "plan configuration is invalid");
  }
  const allowed = new Set([
    "package.json",
    INSTALL_CONFIG_FILE,
    plan.configuration.entryFile,
    plan.configuration.integrationFile,
  ]);
  const seen = new Set<string>();
  for (const change of plan.changes) {
    const normalized = change.path.replaceAll("\\", "/");
    const destination = resolve(plan.targetDir, normalized);
    const insideTarget = destination.startsWith(`${plan.targetDir}${sep}`);
    if (isAbsolute(change.path) || !insideTarget || !allowed.has(normalized)) issues.push(`plan contains an unauthorized path: ${change.path}`);
    if (seen.has(normalized)) issues.push(`plan contains a duplicate path: ${change.path}`);
    seen.add(normalized);
  }
  if (seen.size !== allowed.size || [...allowed].some((path) => !seen.has(path))) issues.push("plan does not contain the exact installer change set");
  if (plan.planId !== planIdentifier(plan.targetDir, plan.configuration, plan.changes)) issues.push("planId does not match the plan contents");
  return issues;
}

export function applyInstallPlan(plan: InstallPlan, options: ApplyOptions = {}): ApplyResult {
  if (plan.status !== "ready" || plan.configuration === null) {
    return {
      v: 1,
      command: "apply",
      status: "blocked",
      targetDir: plan.targetDir,
      planId: plan.planId,
      changedFiles: [],
      unchangedFiles: [],
      installCommand: plan.installCommand,
      installExitCode: null,
      issues: ["only a ready plan can be applied"],
    };
  }
  const invalid = validateReadyPlan(plan);
  if (invalid.length > 0) {
    return {
      v: 1,
      command: "apply",
      status: "blocked",
      targetDir: plan.targetDir,
      planId: plan.planId,
      changedFiles: [],
      unchangedFiles: [],
      installCommand: plan.installCommand,
      installExitCode: null,
      issues: invalid,
    };
  }
  const conflicts: string[] = [];
  for (const change of plan.changes) {
    const current = readText(join(plan.targetDir, change.path));
    const currentHash = current === null ? null : sha256(current);
    if (currentHash !== change.beforeSha256 && current !== change.content) conflicts.push(change.path);
  }
  if (conflicts.length > 0) {
    return {
      v: 1,
      command: "apply",
      status: "blocked",
      targetDir: plan.targetDir,
      planId: plan.planId,
      changedFiles: [],
      unchangedFiles: [],
      installCommand: plan.installCommand,
      installExitCode: null,
      issues: [`files changed after planning: ${conflicts.join(", ")}`],
    };
  }

  const changedFiles: string[] = [];
  const unchangedFiles: string[] = [];
  for (const change of plan.changes) {
    const path = join(plan.targetDir, change.path);
    if (readText(path) === change.content) {
      unchangedFiles.push(change.path);
      continue;
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, change.content, "utf8");
    changedFiles.push(change.path);
  }

  let installExitCode: number | null = null;
  if (options.install === true && plan.installCommand !== null) {
    const [command, ...args] = plan.installCommand;
    if (command !== undefined) {
      const result = spawnSync(command, args, {
        cwd: plan.targetDir,
        stdio: options.quiet === true ? "pipe" : "inherit",
      });
      installExitCode = result.status ?? 1;
    }
  }
  return {
    v: 1,
    command: "apply",
    status: installExitCode === null || installExitCode === 0 ? "applied" : "blocked",
    targetDir: plan.targetDir,
    planId: plan.planId,
    changedFiles,
    unchangedFiles,
    installCommand: plan.installCommand,
    installExitCode,
    issues: installExitCode !== null && installExitCode !== 0 ? [`dependency installation exited ${installExitCode}`] : [],
  };
}

function loadInstallConfiguration(targetDir: string): InstallConfiguration | null {
  const content = readText(join(targetDir, INSTALL_CONFIG_FILE));
  if (content === null) return null;
  try {
    const value = JSON.parse(content) as InstallConfiguration;
    if (value.v !== INSTALL_SCHEMA_VERSION || value.package !== "usecalibrate") return null;
    value.manifest = validateManifest(value.manifest);
    validateRoutes(value.routes, value.manifest);
    return value;
  } catch {
    return null;
  }
}

async function runtimeChecks(configuration: InstallConfiguration, options: VerifyOptions): Promise<VerificationCheck[]> {
  if (options.endpoint === undefined || options.writeKey === undefined) return [];
  const endpoint = options.endpoint.replace(/\/$/, "");
  const checks: VerificationCheck[] = [];
  try {
    const health = await fetch(`${endpoint}/healthz`);
    checks.push({ name: "collector-health", ok: health.ok, detail: `GET /healthz returned ${health.status}` });
  } catch (error) {
    checks.push({ name: "collector-health", ok: false, detail: error instanceof Error ? error.message : String(error) });
    return checks;
  }
  const now = Date.now();
  const sessionId = `verify.${now.toString(36)}`;
  const first = configuration.manifest.steps[0];
  const last = configuration.manifest.steps.at(-1);
  if (first === undefined || last === undefined) return [{ name: "runtime-events", ok: false, detail: "manifest has no steps" }];
  const events = [
    { sessionId, seq: 0, ts: now, manifestVersion: configuration.manifest.version, type: "session_start" },
    { sessionId, seq: 1, ts: now + 1, manifestVersion: configuration.manifest.version, type: "page_view", step: first.id, nav: "forward" },
    { sessionId, seq: 2, ts: now + 2, manifestVersion: configuration.manifest.version, type: "page_view", step: last.id, nav: "forward", from: first.id },
    { sessionId, seq: 3, ts: now + 3, manifestVersion: configuration.manifest.version, type: "shipped", totalMs: 3 },
  ];
  try {
    const response = await fetch(`${endpoint}/api/events`, {
      method: "POST",
      headers: { "content-type": "application/json", "X-Calibrate-Write-Key": options.writeKey },
      body: JSON.stringify({ events }),
    });
    const result = await response.json() as { accepted?: number; rejected?: number };
    checks.push({ name: "synthetic-journey", ok: response.ok && result.accepted === events.length, detail: `accepted ${result.accepted ?? 0} of ${events.length} events` });
  } catch (error) {
    checks.push({ name: "synthetic-journey", ok: false, detail: error instanceof Error ? error.message : String(error) });
    return checks;
  }
  try {
    const privacy = await fetch(`${endpoint}/api/events`, {
      method: "POST",
      headers: { "content-type": "application/json", "X-Calibrate-Write-Key": options.writeKey },
      body: JSON.stringify({ events: [{ ...events[0], sessionId: `${sessionId}.privacy`, seq: 0, email: "person@example.com" }] }),
    });
    const privacyResult = await privacy.json() as { accepted?: number; rejected?: number };
    checks.push({ name: "privacy-rejection", ok: privacy.ok && privacyResult.accepted === 0 && privacyResult.rejected === 1, detail: `accepted ${privacyResult.accepted ?? 0}, rejected ${privacyResult.rejected ?? 0}` });
  } catch (error) {
    checks.push({ name: "privacy-rejection", ok: false, detail: error instanceof Error ? error.message : String(error) });
  }
  return checks;
}

export async function verifyInstallation(directory: string, options: VerifyOptions = {}): Promise<VerifyResult> {
  const targetDir = resolve(directory);
  const checks: VerificationCheck[] = [];
  const configuration = loadInstallConfiguration(targetDir);
  checks.push({ name: "install-config", ok: configuration !== null, detail: configuration === null ? `${INSTALL_CONFIG_FILE} is missing or invalid` : `${INSTALL_CONFIG_FILE} is valid` });
  if (configuration !== null) {
    const entry = readText(join(targetDir, configuration.entryFile));
    const integration = readText(join(targetDir, configuration.integrationFile));
    const packageDocument = readPackage(join(targetDir, "package.json"));
    checks.push({ name: "entry-reachable", ok: entry?.includes(ENTRY_MARKER) === true, detail: entry?.includes(ENTRY_MARKER) === true ? `${configuration.entryFile} imports Calibrate` : `${configuration.entryFile} does not contain the Calibrate entry marker` });
    checks.push({ name: "integration-source", ok: integration?.includes(GENERATED_MARKER) === true, detail: integration?.includes(GENERATED_MARKER) === true ? `${configuration.integrationFile} is present` : `${configuration.integrationFile} is missing or unmanaged` });
    checks.push({ name: "package-dependency", ok: packageDocument?.dependencies?.usecalibrate !== undefined, detail: packageDocument?.dependencies?.usecalibrate === undefined ? "usecalibrate is absent from dependencies" : `usecalibrate ${packageDocument.dependencies.usecalibrate}` });
    checks.push(...await runtimeChecks(configuration, options));
  }
  const runtimeRequested = options.endpoint !== undefined || options.writeKey !== undefined;
  if ((options.endpoint === undefined) !== (options.writeKey === undefined)) checks.push({ name: "runtime-credentials", ok: false, detail: "endpoint and write key must be supplied together" });
  return {
    v: 1,
    command: "verify",
    status: checks.every((check) => check.ok) ? "verified" : "failed",
    evidence: runtimeRequested ? "runtime" : "artifact",
    targetDir,
    checks,
  };
}

export async function prepareGuidedInstall(
  directory: string,
  collectorUrl: string,
  routes?: CalibrateRoute[],
): Promise<GuidedInstallPreparation> {
  const targetDir = resolve(directory);
  const collector = await discoverCollector(collectorUrl);
  if (collector.status !== "ready" || collector.endpoint === null || collector.manifest === null) {
    return {
      v: 1,
      command: "install",
      status: "blocked",
      targetDir,
      collector,
      plan: null,
    };
  }
  const plan = planInstall(targetDir, {
    endpoint: collector.endpoint,
    manifest: collector.manifest,
    ...(routes === undefined || routes.length === 0 ? {} : { routes }),
  });
  return {
    v: 1,
    command: "install",
    status: plan.status === "ready" ? "ready" : plan.status,
    targetDir,
    collector,
    plan,
  };
}

export async function completeGuidedInstall(
  preparation: GuidedInstallPreparation,
  options: GuidedInstallOptions = {},
): Promise<GuidedInstallResult> {
  const base = {
    v: 1 as const,
    command: "install" as const,
    targetDir: preparation.targetDir,
    collectorUrl: preparation.collector.endpoint,
    dashboardUrl: preparation.collector.dashboardUrl,
    hosting: {
      browserSdk: "bundled-with-application" as const,
      collector: "existing-standalone-or-embedded-service" as const,
      dashboard: "served-by-collector" as const,
    },
  };
  if (
    preparation.status !== "ready" ||
    preparation.plan?.status !== "ready" ||
    preparation.collector.endpoint === null
  ) {
    return {
      ...base,
      status: "blocked",
      evidence: "none",
      changedFiles: [],
      unchangedFiles: [],
      requiredEnvironment: preparation.plan?.requiredEnvironment ?? [],
      checks: preparation.collector.checks,
      issues: [
        ...preparation.collector.issues,
        ...(preparation.plan?.issues ?? []),
        ...(preparation.plan?.decisions ?? []),
      ],
    };
  }

  const collectorEndpoint = preparation.collector.endpoint;
  const applied = applyInstallPlan(preparation.plan, {
    ...(options.install === undefined ? {} : { install: options.install }),
    ...(options.quiet === undefined ? {} : { quiet: options.quiet }),
  });
  if (applied.status !== "applied") {
    return {
      ...base,
      status: applied.changedFiles.length > 0 ? "partial" : "blocked",
      evidence: applied.changedFiles.length > 0 ? "artifact" : "none",
      changedFiles: applied.changedFiles,
      unchangedFiles: applied.unchangedFiles,
      requiredEnvironment: preparation.plan.requiredEnvironment,
      checks: preparation.collector.checks,
      issues: applied.issues,
    };
  }

  const runtime = options.writeKey === undefined
    ? {}
    : { endpoint: collectorEndpoint, writeKey: options.writeKey };
  const verification = await verifyInstallation(preparation.targetDir, runtime);
  return {
    ...base,
    status: verification.status === "verified" ? "installed" : "partial",
    evidence: verification.evidence,
    changedFiles: applied.changedFiles,
    unchangedFiles: applied.unchangedFiles,
    requiredEnvironment: preparation.plan.requiredEnvironment,
    checks: [...preparation.collector.checks, ...verification.checks],
    issues: verification.status === "verified"
      ? []
      : verification.checks.filter((check) => !check.ok).map((check) => check.detail),
  };
}

export function sidecarManifest(directory: string): string {
  const targetDir = resolve(directory);
  const configuration = loadInstallConfiguration(targetDir);
  if (configuration === null) throw new Error(`${INSTALL_CONFIG_FILE} is missing or invalid`);
  return JSON.stringify(configuration.manifest);
}

export function describeProject(detection: ProjectDetection): string {
  return `${basename(detection.targetDir)}: ${detection.framework}, ${detection.status}`;
}
